import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptCommonModule } from "nativescript-angular/common";

import { AutoGeneratedRoutingModule } from "./auto-generated-routing.module";
import { AutoGeneratedComponentTns } from './auto-generated.component.tns';

@NgModule({
    imports: [
        NativeScriptCommonModule,
        AutoGeneratedRoutingModule
    ],
    declarations: [
        AutoGeneratedComponentTns
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class AutoGeneratedModule { }